version: "3" 
services: 
  reverseproxy: 
    build: 
      context: ./udagram-reverseproxy 
    image: reverseproxy 
  backend_user: 
    build: 
      context: ./udagram-user-api
    image: udagram-user-api
  backend_feed: 
    build: 
      context: ./udagram-feed-api 
    image: udagram-feed-api 
  frontend: 
    build: 
      context: ./udagram-frontend 
    image: udagram-frontend
